#!/usr/bin/env node
'use strict';

const test = require('node:test');
const assert = require('node:assert/strict');
const { mkdtempSync, existsSync, readFileSync, writeFileSync, utimesSync } = require('node:fs');
const { tmpdir } = require('node:os');
const { join, resolve } = require('node:path');
const { spawnSync } = require('node:child_process');

const REPO_ROOT = resolve(__dirname, '..');

function baseEnv(dataDir) {
    return {
        ...process.env,
        PIELARMONIA_DATA_DIR: dataDir,
        AURORADERM_DATA_DIR: dataDir,
        PIELARMONIA_SKIP_ENV_FILE: '1',
        AURORADERM_SKIP_ENV_FILE: '1',
    };
}

function runPhp(script, env) {
    const result = spawnSync('php', ['-r', script], {
        cwd: REPO_ROOT,
        env,
        encoding: 'utf8',
    });
    assert.equal(result.status, 0, result.stderr || result.stdout);
    return result.stdout.trim();
}

function seedStore(dataDir) {
    runPhp(
        `
        require 'lib/common.php';
        require 'lib/business.php';
        require 'lib/storage.php';
        $store = storage_default_store_payload();
        $store['appointments'] = [[
            'id' => 'appt-1',
            'date' => '2026-03-31',
            'time' => '10:00',
            'doctor' => 'Dra. Aurora',
            'service' => 'Consulta dermatologica',
            'name' => 'Paciente Demo',
            'email' => 'paciente@example.com',
            'phone' => '0999999999',
            'status' => 'confirmed',
        ]];
        $store['callbacks'] = [[
            'id' => 'cb-1',
            'telefono' => '0999999999',
            'preferencia' => 'manana',
            'fecha' => '2026-03-31',
            'status' => 'pendiente',
        ]];
        write_store($store, false);
        echo data_dir_path();
        `,
        baseEnv(dataDir)
    );
}

function decodeBackupPayload(backupFile, env) {
    const output = runPhp(
        `
        require 'lib/common.php';
        require 'lib/validation.php';
        require 'lib/business.php';
        require 'lib/storage.php';
        require 'lib/backup.php';
        $raw = file_get_contents(getenv('BACKUP_FILE'));
        $decoded = gzdecode($raw);
        $result = backup_decode_store_payload($decoded);
        echo json_encode($result, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);
        `,
        {
            ...env,
            BACKUP_FILE: backupFile,
        }
    );

    return JSON.parse(output);
}

test('ops/backup.sh creates a gzip snapshot compatible with backup_decode_store_payload', () => {
    const dataDir = mkdtempSync(join(tmpdir(), 'aurora-backup-script-'));
    seedStore(dataDir);

    const result = spawnSync('bash', ['ops/backup.sh'], {
        cwd: REPO_ROOT,
        env: {
            ...baseEnv(dataDir),
            BACKUP_TIMESTAMP: '2026-03-31-13',
        },
        encoding: 'utf8',
    });

    assert.equal(result.status, 0, result.stderr || result.stdout);

    const backupFile = join(dataDir, 'backups', '2026-03-31-13.json.gz');
    assert.equal(existsSync(backupFile), true, 'backup.gz debe existir');

    const decoded = decodeBackupPayload(backupFile, baseEnv(dataDir));
    assert.equal(decoded.ok, true);
    assert.equal(decoded.counts.appointments, 1);
    assert.equal(decoded.counts.callbacks, 1);
});

test('ops/backup.sh prunes hourly snapshots older than the retention window', () => {
    const dataDir = mkdtempSync(join(tmpdir(), 'aurora-backup-prune-'));
    seedStore(dataDir);

    const backupDir = join(dataDir, 'backups');
    const staleBackup = join(backupDir, '2026-03-20-01.json.gz');
    writeFileSync(staleBackup, 'stale-backup');
    const oldTime = new Date('2026-03-20T01:00:00Z');
    utimesSync(staleBackup, oldTime, oldTime);

    const result = spawnSync('bash', ['ops/backup.sh'], {
        cwd: REPO_ROOT,
        env: {
            ...baseEnv(dataDir),
            BACKUP_TIMESTAMP: '2026-03-31-14',
            BACKUP_RETENTION_DAYS: '7',
        },
        encoding: 'utf8',
    });

    assert.equal(result.status, 0, result.stderr || result.stdout);
    assert.equal(existsSync(staleBackup), false, 'backups viejos deben rotarse');
    assert.equal(
        existsSync(join(backupDir, '2026-03-31-14.json.gz')),
        true,
        'el snapshot nuevo debe mantenerse'
    );
});

test('restore-backup accepts gzip snapshots generated by ops/backup.sh', () => {
    const dataDir = mkdtempSync(join(tmpdir(), 'aurora-backup-restore-'));
    seedStore(dataDir);

    const env = {
        ...baseEnv(dataDir),
        BACKUP_TIMESTAMP: '2026-03-31-15',
    };

    const backupResult = spawnSync('bash', ['ops/backup.sh'], {
        cwd: REPO_ROOT,
        env,
        encoding: 'utf8',
    });
    assert.equal(backupResult.status, 0, backupResult.stderr || backupResult.stdout);

    runPhp(
        `
        require 'lib/common.php';
        require 'lib/business.php';
        require 'lib/storage.php';
        $store = storage_default_store_payload();
        write_store($store, false);
        `,
        baseEnv(dataDir)
    );

    const restoreResult = spawnSync(
        'php',
        ['bin/restore-backup.php', join(dataDir, 'backups', '2026-03-31-15.json.gz'), '--force'],
        {
            cwd: REPO_ROOT,
            env: baseEnv(dataDir),
            encoding: 'utf8',
        }
    );

    assert.equal(restoreResult.status, 0, restoreResult.stderr || restoreResult.stdout);

    const restoredCounts = JSON.parse(
        runPhp(
            `
            require 'lib/common.php';
            require 'lib/business.php';
            require 'lib/storage.php';
            $store = read_store();
            echo json_encode([
                'appointments' => count($store['appointments'] ?? []),
                'callbacks' => count($store['callbacks'] ?? []),
            ]);
            `,
            baseEnv(dataDir)
        )
    );

    assert.equal(restoredCounts.appointments, 1);
    assert.equal(restoredCounts.callbacks, 1);
});
