'use strict';

function toTaskJson(task) {
    return {
        id: String(task?.id || ''),
        title: String(task?.title || ''),
        owner: String(task?.owner || ''),
        executor: String(task?.executor || ''),
        status: String(task?.status || ''),
        risk: String(task?.risk || ''),
        scope: String(task?.scope || ''),
        codex_instance: String(task?.codex_instance || ''),
        domain_lane: String(task?.domain_lane || ''),
        lane_lock: String(task?.lane_lock || ''),
        cross_domain: Boolean(task?.cross_domain),
        provider_mode: String(task?.provider_mode || ''),
        runtime_surface: String(task?.runtime_surface || ''),
        runtime_transport: String(task?.runtime_transport || ''),
        runtime_last_transport: String(task?.runtime_last_transport || ''),
        model_tier_default: String(task?.model_tier_default || ''),
        premium_budget: Number(task?.premium_budget || 0),
        premium_calls_used: Number(task?.premium_calls_used || 0),
        premium_gate_state: String(task?.premium_gate_state || ''),
        decision_packet_ref: String(task?.decision_packet_ref || ''),
        model_policy_version: String(task?.model_policy_version || ''),
        strategy_id: String(task?.strategy_id || ''),
        subfront_id: String(task?.subfront_id || ''),
        strategy_role: String(task?.strategy_role || ''),
        strategy_reason: String(task?.strategy_reason || ''),
        focus_id: String(task?.focus_id || ''),
        focus_step: String(task?.focus_step || ''),
        integration_slice: String(task?.integration_slice || ''),
        work_type: String(task?.work_type || ''),
        expected_outcome: String(task?.expected_outcome || ''),
        decision_ref: String(task?.decision_ref || ''),
        rework_parent: String(task?.rework_parent || ''),
        rework_reason: String(task?.rework_reason || ''),
        workspace_machine_id: String(task?.workspace_machine_id || ''),
        workspace_branch: String(task?.workspace_branch || ''),
        workspace_head: String(task?.workspace_head || ''),
        workspace_origin_main_head: String(
            task?.workspace_origin_main_head || ''
        ),
        workspace_sync_state: String(task?.workspace_sync_state || ''),
        workspace_sync_checked_at: String(task?.workspace_sync_checked_at || ''),
        files: Array.isArray(task?.files) ? task.files : [],
        acceptance_ref: String(task?.acceptance_ref || ''),
        updated_at: String(task?.updated_at || ''),
    };
}

function toTaskFullJson(task) {
    return {
        id: String(task?.id || ''),
        title: String(task?.title || ''),
        owner: String(task?.owner || ''),
        executor: String(task?.executor || ''),
        status: String(task?.status || ''),
        risk: String(task?.risk || ''),
        scope: String(task?.scope || ''),
        codex_instance: String(task?.codex_instance || ''),
        domain_lane: String(task?.domain_lane || ''),
        lane_lock: String(task?.lane_lock || ''),
        cross_domain: Boolean(task?.cross_domain),
        provider_mode: String(task?.provider_mode || ''),
        runtime_surface: String(task?.runtime_surface || ''),
        runtime_transport: String(task?.runtime_transport || ''),
        runtime_last_transport: String(task?.runtime_last_transport || ''),
        model_tier_default: String(task?.model_tier_default || ''),
        premium_budget: Number(task?.premium_budget || 0),
        premium_calls_used: Number(task?.premium_calls_used || 0),
        premium_gate_state: String(task?.premium_gate_state || ''),
        decision_packet_ref: String(task?.decision_packet_ref || ''),
        model_policy_version: String(task?.model_policy_version || ''),
        strategy_id: String(task?.strategy_id || ''),
        subfront_id: String(task?.subfront_id || ''),
        strategy_role: String(task?.strategy_role || ''),
        strategy_reason: String(task?.strategy_reason || ''),
        focus_id: String(task?.focus_id || ''),
        focus_step: String(task?.focus_step || ''),
        integration_slice: String(task?.integration_slice || ''),
        work_type: String(task?.work_type || ''),
        expected_outcome: String(task?.expected_outcome || ''),
        decision_ref: String(task?.decision_ref || ''),
        rework_parent: String(task?.rework_parent || ''),
        rework_reason: String(task?.rework_reason || ''),
        workspace_machine_id: String(task?.workspace_machine_id || ''),
        workspace_branch: String(task?.workspace_branch || ''),
        workspace_head: String(task?.workspace_head || ''),
        workspace_origin_main_head: String(
            task?.workspace_origin_main_head || ''
        ),
        workspace_sync_state: String(task?.workspace_sync_state || ''),
        workspace_sync_checked_at: String(task?.workspace_sync_checked_at || ''),
        files: Array.isArray(task?.files) ? task.files : [],
        acceptance: String(task?.acceptance || ''),
        acceptance_ref: String(task?.acceptance_ref || ''),
        depends_on: Array.isArray(task?.depends_on) ? task.depends_on : [],
        prompt: String(task?.prompt || ''),
        created_at: String(task?.created_at || ''),
        updated_at: String(task?.updated_at || ''),
    };
}

module.exports = {
    toTaskJson,
    toTaskFullJson,
};
