name: PHP Syntax Linter

on:
  push:
    branches: [ "main", "staging" ]
  pull_request:
    branches: [ "main", "staging" ]

jobs:
  php-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        
    - name: Run PHP Syntax Linter
      run: |
        find controllers/ lib/ -name "*.php" | xargs -I{} php -l {}
